// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvkfqovfzguyslvdudqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2a2Zxb3Zmemd1eXNsdmR1ZHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDUxNzMsImV4cCI6MjA3MjU4MTE3M30.YpfN1WDZsjlUwJuvhZlSskCbsTG-DURuowZGADR7h9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});